### ISSUE TITLE
A Few Requests

### ISSUE THREAD

**Issue by PureOcean** [Dither/smart-rss#2]
Dear **_Dither_**,

Firstly, thank you for the fork. Secondly, I'm sorry my bad English.

I still use original **SmarRSS** extension in Cent Browser (which it chromium-based). SmartRSS is a really great extension. If **Martin** hadn't let to develop this extension, I would have a few requests. I search a fork of this extension in Github. So, I discovered the **your fork**. 

I just tried. If you're still interested, I would like to give my request.

1) I have many feeds URL. When I imported my **OPML** file, the extension is having a lot of trouble getting all feeds from all URLs. I manually selects all the folders and the _Update -> Never / Disabled_. It's don't accept, it continue downloading feeds. However, original SmartRSS suddenly don't stop feeds download, if "Never" option is select in Update setting.

2) Feature request: "_Don't update/take titles of all feeds immediately after the OPML importing._"  That is to say, after Import, can be add only Feed URL with folders.

3) I think, this fork is unstable according to original SmartRSS. Maybe this issue can be releated to [**CentBrowser**](https://www.centbrowser.com/). I want send to you my OPML file. But I don't know your e-mail address. Could you test your in Cent?

4) While original SmartRSS version 2.0 in [Github](https://github.com/martinkadlec0/Smart-RSS), the version **2.2.1** in [Opera add-on page](https://addons.opera.com/en/extensions/details/smart-rss/). I tried both of them. Version 2.2.1 is better.

5) You may add more information to Settings (pop-up) of your fork. Version info, Original Author's and your name and github adress. For now, very simply: "dev build". No mentioned current version, names of the developer & forker.

6) Feature: "_Compact to feed stores_". Original SmartRSS' LDB files really very sizable in IndexedDB folder. I think, still keep all feed in files even If all feeds titles to deleted.

7) It would be useful added to the "Properties" button next to the "Update all" button in the toolbar at the top left.

I'm grateful that you read this message.
Thank you in advance.

**Comment by Dither** [comment]
This version is private fork and isn't supposed to be actively maintained, It was heavily modified so it's useless to compare it with 2.2.1 on which it was based on.

**Comment by Dither** [comment]
This is fork intended for private use only. It's open-source so if someone interested they can fork it and continue the modifications. I won't be adding any new functionality unless I need it. I'll try to fix OPML import when I'll need the extension again, but not in the near future because I neither use nor develop it lately.
